### ISSUE TITLE
Remove comments from Docker/S2I components

### ISSUE THREAD

**Issue by sabre1041** [openshift-s2i/s2i-aspnet#17]
There are a number of commented out items in the Dockerfile and S2I scripts. Remove and cleanup prior to GA release

**Comment by alberttwong** [comment]
I did that so that people knew the mapping from the official MS docker image and then what we did to convert it to s2i.

**Comment by sabre1041** [comment]
Builder is no longer utilizing any components from MS docker image. Closing
